FROM quay.io/keycloak/keycloak:12.0.1

USER root

EXPOSE 8080
EXPOSE 9990

ARG CONT_DIR
ARG HOST_CFG_DIR
ARG HOST_DIR
ARG SYS_DIR

RUN echo CONT_DIR is ${CONT_DIR}
RUN echo HOST_CFG_DIR is ${HOST_CFG_DIR}
RUN echo HOST_DIR is ${HOST_DIR}
RUN echo SYS_DIR is ${SYS_DIR}
RUN echo USER is ${USER}

RUN mkdir -p $CONT_DIR
WORKDIR ${CONT_DIR}

#RUN mkdir /etc/nginx/available_sites
#COPY ${SYS_DIR}/keycloak/realm-export.json ${CONT_DIR}/standalone/

